domain: your.domain.com
# Requests for these domains will be redirected to the actual domain.
redirects:
  - other.domain.com
  - other.domain1.com
# Enables debug mode for gunicorn. Do NOT enable this in production.
tatorDebug: true
# Enables javascript minification.
useMinJs: false
# Enable this to turn on "down for maintenance" page.
maintenance: false
nginxReplicas: 1
gunicornReplicas: 1 
djangoSecretKey: "<Your django secret key>"
postgresHost: "pgbouncer-svc"
postgresUsername: "<Your postgres username>"
postgresPassword: "<Your postgres password>"
redisHost: "tator-redis-master"
elasticsearchHost: "elasticsearch-master"
dockerUsername: "test"
dockerPassword: "test"
dockerRegistry: "localhost:5000"
systemImageRepo: "localhost:5000"
slackToken: "<Your slack API token>" # Optional, for slack notifications
slackChannel: "<Your slack channel ID>" # Optional, for slack notifications
sslBundle: |
  -----BEGIN CERTIFICATE-----
  <Insert certificate here>
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  <Insert certificate here>
  -----END CERTIFICATE-----
sslKey: |
  -----BEGIN PRIVATE KEY-----
  <Insert private key here>
  -----END PRIVATE KEY-----
pv:
  enabled: true
  nfsServer: "192.168.1.114"
  nfsMountOptions:
    - nfsvers=3
    - nolock
  staticPath: "/media/kubernetes_share/static"
  uploadPath: "/media/kubernetes_share/upload"
  mediaPath: "/media/kubernetes_share/media"
  rawPath: "/media/kubernetes_share/raw"
  backupPath: "/media/kubernetes_share/backup"
  migrationsPath: "/media/kubernetes_share/migrations"
pvc:
  staticSize: 1Gi
  uploadSize: 1Ti
  mediaSize: 4Ti
  rawSize: 6Ti
  backupSize: 100Gi
  migrationsSize: 1Gi
hpa:
  nginxMinReplicas: 1
  nginxMaxReplicas: 10
  nginxCpuPercent: 50
  gunicornMinReplicas: 1
  gunicornMaxReplicas: 10
  gunicornCpuPercent: 50
  daphneMinReplicas: 1
  daphneMaxReplicas: 10
  daphneCpuPercent: 50
  tusdMinReplicas: 1
  tusdMaxReplicas: 10
  tusdCpuPercent: 50
metallb:
  # Enable this to provide a load balancer implementation on bare metal.
  enabled: true
  ipRangeStart: 192.168.1.220
  ipRangeStop: 192.168.1.224
  loadBalancerIp: 192.168.1.221
postgis:
  # Enable this if you want to use the postgis docker image.
  enabled: true
  persistence:
    size: 10Gi
  hostPath: /media/ssd/postgis
redis:
  # Enable this to install the redis helm chart.
  enabled: true
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  nodeSelector:
    dbServer: "yes"
  usePassword: false
metrics-server:
  enabled: true
  args:
    - --v=2
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP
elasticsearch:
  # Enable this to install the elasticsearch helm chart.
  enabled: true
  persistence:
    enabled: true
  replicas: 1
  clusterHealthCheckParams: wait_for_status=yellow&timeout=1s
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 30Gi
  nodeSelector: 
    dbServer: "yes"
  hostPath: /media/ssd/elasticsearch
filebeat:
  enabled: true
kibana:
  enabled: true
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /logs
cluster-autoscaler:
  # Should be disabled for bare metal.
  enabled: false
awsStorage:
  # Should be disabled for bare metal.
  enabled: false
remoteTranscodes:
  # Typically for dev processing is done on the same machine.
  enabled: false
  # Host/port are obtained via the following (run on the transcode cluster):
  #   echo $(kubectl config view --minify | grep server | cut -f 2- -d ":" | tr -d " ")
  host: "your.transcode.domain.org"
  port: "6443"
  # Token can be obtained via the following (run on the transcode cluster):
  #   SECRET_NAME=$(kubectl get secrets | grep ^default | cut -f1 -d ' ')
  #   TOKEN=$(kubectl describe secret $SECRET_NAME | grep -E '^token' | cut -f2 -d':' | tr -d " ")
  #   echo $TOKEN
  token: "Bearer <Your token here>"
  # Certificate can be obtained via the following (run on the transcode cluster):
  #   SECRET_NAME=$(kubectl get secrets | grep ^default | cut -f1 -d ' ')
  #   CERT=$(kubectl get secret $SECRET_NAME -o yaml | grep -E '^  ca.crt' | cut -f2 -d':' | tr -d " ")
  #   echo $CERT | base64 --decode
  cert: |
    -----BEGIN CERTIFICATE-----
    <Insert certificate here>
    -----END CERTIFICATE-----

